### ISSUE TITLE
Beware of loading issues

### ISSUE THREAD

**Issue by sbutlerjr** [Servoy/svyTabPanelPlus#3]
This port of Servoy's default tabpanel is a bit behind where it was forked from, and while there have been several commits with fixes, a new release hasn't been made yet.  I had a customer using this and would get random reports from users where tabs in related tabpanels would seem out of sync with the assigned relationship.  It was impossible to duplicate on demand, but would repeat once a month or so.  Not sure this is quite production worthy in all use-cases, so just sharing that experience here to prevent some headache of others.  Hopefully this port gets more regular updates.

**Comment by seanthomasdevlin** [comment]
Hi Scott.
As you pointed out this package is lagging behind. We have actually ported its functionality to the bootstrap tabpanel. It also makes not much sense to have two extra tabpanel components essentially with the same job.

This package is essentially end-of-life. Sorry we didn't announce anything yet, but it I thought we worked directly with the only people using this component.

You should be able to get the same functionality from the [bootstrap components package](https://github.com/Servoy/bootstrapcomponents/releases/latest).

**Comment by sbutlerjr** [comment]
Thanks Sean.  2 things that could be helpful here:

1.  This still shows up in the Web Package Manager, so unknowing customers that don't look at git issues will install it and think its safe to use.  I'd suggest removing it.

2.  It would be nice if the WPM functionality had an option to notify end-of-life, in the same way it can show updates.  This way you can easily notify all customers using the component when something reaches end-of-life.
